jwt:
  secret: FBIB54IBIU45B7I54B7I4B7I4B7I4B7IVGBUI
  expirationDateInMs: 10 000
  refreshExpirationDateInMs: 86400000

spring:
  profiles:
    active: ${APP_PROFILE:dev}
  jpa:
    open-in-view: false
