#spring.jpa.properties.javax.persistence.schema-generation.create-source=metadata
#spring.jpa.properties.javax.persistence.schema-generation.scripts.action=create
#spring.jpa.properties.javax.persistence.schema-generation.scripts.create-target=create.sql
#spring.jpa.properties.hibernate.hbm2ddl.delimiter=;
#spring.jpa.hibernate.ddl-auto=none

spring:
  datasource:
    url: jdbc:postgresql://localhost:5432/task-service
    username: postgres
    password: postgres
  jpa:
    hibernate:
      ddl-auto: update
      generate-ddl: true

