
#spring.jpa.hibernate.ddl-auto=none

spring:
  datasource:
    url: jdbc:postgresql://localhost:5432/task-service
    username: postgres
    password: postgres
  jpa:
    hibernate:
      ddl-auto: update
      generate-ddl: true
    properties:
      javax:
        persistence:
          schema-generation:
            create-source: metadata
            scripts:
              action: create
              create-target: create.sql