version: '3.8'

services:
  db:
    image: postgres
    ports:
      - 5432:5432
    environment:
      POSTGRES_USERNAME: postgres
      POSTGRES_PASSWORD: postgres
      POSTGRES_DB: task-service

    volumes:
      - /var/lib/postgres/data