jwt:
  secret: FBIB54IBIU45B7I54B7I4B7I4B7I4B7IVGBUI
  expirationDateInMs: 10 000
  refreshExpirationDateInMs: 86400000


spring:
  mail:
    host: smtp.gmail.com
    port: 587
    username: pelosi.todo.app@gmail.com
    password: todoapp@pelosi
    properties:
      mail:
        smtp:
          auth: true
          starttls:
            enable: true
  profiles:
    active: ${APP_PROFILE:dev}
  jpa:
    open-in-view: false
