spring:
  cloud:
    config:
      server:
        git:
          uri: https://github.com/GabrielPelosi/todo-config-server-files.git
        password:
        username:
        clone-on-start: true

  application:
    name: config-server

server:
  port: 8088
